/* GENERATED BY testvec_tool, DO NOT EDIT */

#pragma once

#include "testvec.h"

struct hctr2_testvec {
	struct testvec_buffer key;
	struct testvec_buffer tweak;
	struct testvec_buffer plaintext;
	struct testvec_buffer ciphertext;
};

extern const struct hctr2_testvec hctr2_aes128_tv[];
extern const size_t hctr2_aes128_tv_count;

extern const struct hctr2_testvec hctr2_aes192_tv[];
extern const size_t hctr2_aes192_tv_count;

extern const struct hctr2_testvec hctr2_aes256_tv[];
extern const size_t hctr2_aes256_tv_count;
