/* GENERATED BY testvec_tool, DO NOT EDIT */

#pragma once

#include "testvec.h"

struct polyval_testvec {
	struct testvec_buffer key;
	struct testvec_buffer message;
	struct testvec_buffer hash;
};

extern const struct polyval_testvec polyval_tv[];
extern const size_t polyval_tv_count;
