/* GENERATED BY testvec_tool, DO NOT EDIT */

#pragma once

#include "testvec.h"

struct xctr_testvec {
	struct testvec_buffer key;
	struct testvec_buffer nonce;
	struct testvec_buffer plaintext;
	struct testvec_buffer ciphertext;
};

extern const struct xctr_testvec xctr_aes128_tv[];
extern const size_t xctr_aes128_tv_count;

extern const struct xctr_testvec xctr_aes192_tv[];
extern const size_t xctr_aes192_tv_count;

extern const struct xctr_testvec xctr_aes256_tv[];
extern const size_t xctr_aes256_tv_count;
