#!/usr/bin/env python3
#
# Copyright 2018 Google LLC
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

import importlib
import sys

import cipherlist
import paths
import tvgen

verbose = False
path = paths.top / "test_vectors" / "ours"


def write(ciphers):
    if ciphers is None:
        ciphers = cipherlist.ciphers
    for cipher in ciphers:
        tvgen.write_tests(cipher, path)


def check(ciphers):
    for cipher in ciphers:
        test = cipher.name().lower()
        print(f"======== {test} ========")
        testmod = importlib.import_module(f"test_{test}")
        for r in testmod.test_vectors(cipher):
            tvgen.check_testvector(cipher, r, verbose)
        tvgen.check_tests(cipher, path, verbose)


def main():
    if len(sys.argv) not in [2, 3]:
        raise Exception("Bad args: {} use write or check".format(sys.argv[1:]))
    command = sys.argv[1]
    ciphers = cipherlist.ciphers
    if len(sys.argv) == 3:
        ciphers = [c for c in cipherlist.ciphers if c.name() ==
                   sys.argv[2]]
        if not ciphers:
            raise Exception(f"No cipher known called {sys.argv[2]}")
    if command == "write":
        write(ciphers)
    elif command == "check":
        check(ciphers)
    else:
        raise Exception("Bad args: {} use write or check".format(sys.argv[1:]))


if __name__ == "__main__":
    main()
