#
# Copyright 2021 Google LLC
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.
#

name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CRYPTOBENCH_DEPENDENCIES: python3 python3-crypto meson ninja-build

jobs:
  test-python:
    name: Test python code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-crypto
    - name: Test python code
      run: |
        ./python/testvec_tool check

  test-cryptobench-x86_64:
    name: Build and run benchmark tool (x86_64)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y $CRYPTOBENCH_DEPENDENCIES
    - name: Build benchmark tool
      run: |
        cd benchmark
        meson build/host --werror
        ninja -C build/host
    - name: Run benchmark tool
      run: |
        ./benchmark/build/host/cipherbench --ntries=1

  test-cryptobench-qemu-aarch64:
    name: Build and run benchmark tool (qemu-aarch64)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y $CRYPTOBENCH_DEPENDENCIES \
                qemu-user binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu
    - name: Build benchmark tool
      run: |
        cd benchmark
        ./cross-tools/setup-build --build-type=qemu-aarch64 -- --werror
        ninja -C build/qemu-aarch64
    - name: Run benchmark tool
      run: |
        qemu-aarch64 -L /usr/aarch64-linux-gnu \
               ./benchmark/build/qemu-aarch64/cipherbench --ntries=1

  check-latex:
    name: Check LaTeX sources
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-extra texlive-luatex texlive-science biber
    - name: Check LaTeX
      run: |
        ./paper/build.sh
